### ISSUE TITLE
Autofix broken for index file imports

### ISSUE THREAD

**Issue by trevor-scheer** [solana-labs/eslint-plugin-require-extensions#2]
Index files are often imported by the name of the folder that contains them,
i.e. a file with modules:
`./externalTypes/index.js`

could be imported like so:
`import * from ./externalTypes`.

Once an extension is added, however, the `index` file needs to be specified correctly. The expected lint fix behavior for the above would be:
`import * from ./externalTypes/index.js`

...but the observed behavior is:
`import * from ./externalTypes.js`
(which is a file that doesn't exist)

To reproduce:
```
git clone git@github.com:apollographql/apollo-server.git
git checkout trevor/import-lint
```

Open `apollo-server/packages/server/src/ApolloServer.ts`
Remove `/index.js` from L54 import (`./externalTypes/index.js`)
Trigger autofix (via save), note the incorrect import.

For the last step...it seems like VSCode is using our eslint config correctly but the CLI isn't for some reason (news to me). If reproduction via editor is insufficient let me know and I can try to get that resolved so that my last step in the reproduction can become `npx eslint . --fix`.

**Comment by tpluscode** [comment]
Are you sure that `import * from ./externalTypes` is a valid ES import? I would think that for relative paths they must be exact.

The extensionless modules are only valid when importing a module explicitly listed in package.json `exports`

**Comment by trevor-scheer** [comment]
I'm not sure I understand your question. My understanding is that this plugin exists to lint against and correct invalid imports which are missing the extension.

So directly, no, `import * from ./externalTypes` is not a valid ES import (since it has no extension). But this plugin is here to detect and correct it to the right thing (which I am very happy about).

What I'm suggesting is that the autofix behavior is incorrect for this scenario. The fixer needs to be aware of the existence of the file. If it doesn't exist, it should look to see if there's an `index` file in that path and use it appropriately.

So, since there is no actual `externalTypes.js` file, it should then look for an `externalTypes/index` file and use that in the fix if it exists. Hopefully that makes sense, let me know if anything is unclear.

**Comment by tpluscode** [comment]
Sorry, I expressed myself poorly. IMO, the plugin behaves as expected: it adds extension to an import.

I suppose it could be implemented to check for the existence of `./index.(ts|js)` and fix accordingly. I would just propose to cater for the edge case where both `./externalTypes.ts` and `./externalTypes/index.ts` exist. In such case there should be no auto-fix to ensure that the correct alternative is chose.

**Comment by trevor-scheer** [comment]
Agreed. I'm not sure if or when I'd get to it, but would you be open to a PR that implements that? If the answer is yes and someone beats me to it that's fine too 😄

**Comment by tpluscode** [comment]
I'm not the author here. I just opened another PR myself recently. Not saying I would not open the PR but no promises ;)

**Comment by trevor-scheer** [comment]
Oh, whoops! I just assumed. Thanks for letting me know.

**Comment by tpluscode** [comment]
Just a quick not before I forget. Rather than checking for the `index.??` file, the code would better check whether the given path is a dir and in such case append `/index.js`, which would equally work for JS and TS.

Would still fail for `index.mjs` but that might be a rare case, requiring manual fix

**Comment by jordansexton** [comment]
https://github.com/solana-labs/eslint-plugin-require-extensions/pull/3#issuecomment-1411124347

@tpluscode's fix for non-JS imports was just merged and released. I think a slightly modified approach could work for this issue also. I personally use index imports and run into this quite a bit.

**Comment by tpluscode** [comment]
I use index import too. One that I added your plugin to my base config I'm surely going to hit this issue on occasion.

Happy to submit a PR when this happens
