### ISSUE TITLE
Allow "parametrised" imports

### ISSUE THREAD

**Issue by tpluscode** [solana-labs/eslint-plugin-require-extensions#5]
Web bundlers such as vite or webpack, allow adding "query strings" to import paths to trigger special behaviour.

For example, vite has a built-in feature to load any file as string by appending `?raw` to the module path.

I fixed that on a branch and will be happy to submit a PR once #4 is merged

**Comment by jordansexton** [comment]
Ah, good call. I haven't used that feature in Webpack in a few years, so I didn't consider it, but I think that's a good addition.
